export interface iAuthData {
  consumer_key: string;
  consumer_secret: string;
  access_token: string;
  access_token_secret: string;
}

// Autogenerated with https://transform.tools/json-to-typescript
export type RecentTweetsResponse = {
  data: Array<{
    created_at: string;
    public_metrics: {
      retweet_count: number;
      reply_count: number;
      like_count: number;
      quote_count: number;
    };
    text: string;
    author_id: string;
    id: string;
    entities?: {
      mentions?: Array<{
        start: number;
        end: number;
        username: string;
        id: string;
      }>;
      annotations?: Array<{
        start: number;
        end: number;
        probability: number;
        type: string;
        normalized_text: string;
      }>;
      urls?: Array<{
        start: number;
        end: number;
        url: string;
        expanded_url: string;
        display_url: string;
        images?: Array<{
          url: string;
          width: number;
          height: number;
        }>;
        status?: number;
        title?: string;
        description?: string;
        unwound_url?: string;
        media_key?: string;
      }>;
    };
    attachments?: {
      poll_ids?: Array<string>;
      media_keys?: Array<string>;
    };
  }>;
  includes: {
    users: Array<{
      profile_image_url: string;
      name: string;
      username: string;
      id: string;
      url: string;
    }>;
  };
  meta: {
    newest_id: string;
    oldest_id: string;
    result_count: number;
    next_token: string;
  };
};

// Autogenerated with https://transform.tools/json-to-typescript
export type ConversationResponse = {
  data: Array<{
    id: string;
    entities: {
      mentions: Array<{
        start: number;
        end: number;
        username: string;
        id: string;
      }>;
      annotations?: Array<{
        start: number;
        end: number;
        probability: number;
        type: string;
        normalized_text: string;
      }>;
    };
    public_metrics: {
      retweet_count: number;
      reply_count: number;
      like_count: number;
      quote_count: number;
    };
    created_at: string;
    text: string;
    author_id: string;
  }>;
  includes: {
    users: Array<{
      id: string;
      username: string;
      profile_image_url: string;
      name: string;
      url: string;
    }>;
  };
  meta: {
    newest_id: string;
    oldest_id: string;
    result_count: number;
    next_token: string;
  };
};

// Autogenerated with https://transform.tools/json-to-typescript
export type SingleTweetResponse = {
  data: {
    text: string;
    created_at: string;
    public_metrics: {
      retweet_count: number;
      reply_count: number;
      like_count: number;
      quote_count: number;
    };
    entities: {
      urls: Array<{
        start: number;
        end: number;
        url: string;
        expanded_url: string;
        display_url: string;
        media_key: string;
      }>;
      annotations: Array<{
        start: number;
        end: number;
        probability: number;
        type: string;
        normalized_text: string;
      }>;
    };
    author_id: string;
    attachments: {
      media_keys: Array<string>;
    };
    id: string;
  };
  includes: {
    users: Array<{
      username: string;
      name: string;
      profile_image_url: string;
      url: string;
      id: string;
    }>;
  };
};
